spring:
  config:
    import: optional:file:docker/.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true


keycloak:
  openid-connect-url: ${KEYCLOAK_OPENID_URL_USER}
  url: ${KEYCLOACK_HOST}
  realm: ${KEYCLOACK_REALM_NAME}
  clientId: ${KEYCLOACK_CLIENT_ID}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}
  username: ${KEYCLOAK_ADMIN_USER}
  password: ${KEYCLOAK_ADMIN_PASSWORD}

server:
  port: 8081
